name: ci

on:
  push:
    branches: [main, master]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ¬ Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: ğŸ¬ Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: ğŸš€ Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: drack112/discord-music-bot:latest
          build-args: |
      - name: ğŸš€ Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
